/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grove;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author seaadmin
 */
public class RNASeqDiffFrame extends javax.swing.JFrame {

    /**
     * Creates new form RNASeqDiffFrame
     */
    public RNASeqDiffFrame() {
        initComponents();
        addActionListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rnaSeqDiffLabel = new javax.swing.JLabel();
        calculateDifferenceButton = new javax.swing.JButton();
        selectCappedFileButton = new javax.swing.JButton();
        selectUncappedFileButton = new javax.swing.JButton();
        cappedFileNameLabel = new javax.swing.JLabel();
        uncappedFileNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rnaSeqDiffLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        rnaSeqDiffLabel.setText("RNA-Seq Diff");
        rnaSeqDiffLabel.setToolTipText("");

        calculateDifferenceButton.setText("Calculate Difference");

        selectCappedFileButton.setText("Select Capped File");

        selectUncappedFileButton.setText("Select Uncapped File");

        cappedFileNameLabel.setText("Capped File Name");

        uncappedFileNameLabel.setText("Uncapped File Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(selectCappedFileButton))
                            .addComponent(selectUncappedFileButton))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cappedFileNameLabel)
                            .addComponent(uncappedFileNameLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(calculateDifferenceButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(rnaSeqDiffLabel)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rnaSeqDiffLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCappedFileButton)
                    .addComponent(cappedFileNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectUncappedFileButton)
                    .addComponent(uncappedFileNameLabel))
                .addGap(33, 33, 33)
                .addComponent(calculateDifferenceButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RNASeqDiffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RNASeqDiffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RNASeqDiffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RNASeqDiffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RNASeqDiffFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateDifferenceButton;
    private javax.swing.JLabel cappedFileNameLabel;
    private javax.swing.JLabel rnaSeqDiffLabel;
    private javax.swing.JButton selectCappedFileButton;
    private javax.swing.JButton selectUncappedFileButton;
    private javax.swing.JLabel uncappedFileNameLabel;
    // End of variables declaration//GEN-END:variables

private void addActionListeners(){
        RNASeqDiffFrameActionListener listener = new RNASeqDiffFrameActionListener();
        selectCappedFileButton.addActionListener(listener);
        selectUncappedFileButton.addActionListener(listener);
        calculateDifferenceButton.addActionListener(listener);
    }    

public class RNASeqDiffFrameActionListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            Object source = e.getSource();
            
           if(source.equals(selectCappedFileButton)){
               System.out.println("Select capped file");
               System.out.println("Open JFileChooser");
               System.out.println("Get Selected File and store");
               System.out.println("Add name to label");
           }
           
           if(source.equals(selectUncappedFileButton)){
               System.out.println("Select uncapped file");
               System.out.println("Open JFileChooser");
               System.out.println("Get Selected File and store");
               System.out.println("Add name to label");
           }
           
           if(source.equals(calculateDifferenceButton)){
               System.out.println("Calculate Difference");
               System.out.println("Get parameters");
               System.out.println("Run Python Script");
           }
        }
    
}





}
